[[redirects]]
  from = "/api/*"
  to = "https://dashndrop.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, client-id"

